// Generated by Framer (ce6e1ae)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "2x9ogp", mediaQuery: "(min-width: 1200px)"}, {hash: "b60hew", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "f63han", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {rSZjKRN2d: "hero"}, robots: "max-image-preview:large", serializationId: "framer-dBbBD", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1