// Generated by Framer (4458791)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "bbm336"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-yAjC0", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=1200"}
}

export const metadataVersion = 1