// Generated by Framer (4f3879e)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "187ctmn", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "unjy5z", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {DLscFvTjv: "hero", F4PqMtjOQ: "feature-card-4", ft_i33w7Z: "pricing", hyhFYq3pd: "feature", ingCJDzK6: "benefits", nGi7ANL8e: "feature-card-2", NXjzeLxNN: "testimonials", rBVmDJGHl: "overview", rCWmUyods: "pricing-comparison", Sr5O4cgdK: "faq", vVko3CWIP: "feature-card-3", vZ3VC_tUr: "feature-card-1", wb1uPPXbB: "bento", yOiOUxy35: "metrics", ZiVpULg1V: "highlight"}, robots: "max-image-preview:large", serializationId: "framer-B5VNV", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1