// Generated by Framer (b012016)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Instance,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Shapes from "https://framerusercontent.com/modules/SUBEdtCFaOJwrjN2Inhk/bznEUerLEqVVXGfsDOYE/pKERsxd4H.js";
import * as sharedStyle from "https://framerusercontent.com/modules/vetOeLKjkI0x70qPk4hQ/36TGvxQ7gBmZUUbHtWN0/MV92va9oP.js";
const serializationHash = "framer-Fhx2V";
const variantClassNames = {
    EvQTnpjdl: "framer-v-18xhfg8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    icon,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        I483A28Gp: title ? ? props.I483A28Gp ? ? "AI Project Tool",
        rE1bGiPOa: icon ? ? props.rE1bGiPOa ? ? Shapes
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        rE1bGiPOa,
        I483A28Gp,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "EvQTnpjdl",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-18xhfg8", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Badge",
                    layoutDependency: layoutDependency,
                    layoutId: "EvQTnpjdl",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "1px",
                        "--border-color": "var(--token-64e377a5-0d6a-419d-892d-eb08deb7230b, rgb(229, 229, 232))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor: "var(--token-03d81d49-441b-4a27-ac27-adbec865c0a8, rgb(250, 250, 250))",
                        borderBottomLeftRadius: 17,
                        borderBottomRightRadius: 17,
                        borderTopLeftRadius: 17,
                        borderTopRightRadius: 17,
                        boxShadow: "0px 2px 5px 0px var(--token-01b0806d-1c81-4041-802e-d5d50172987c, rgb(240, 241, 242))",
                        ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1l1ajhh",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "OFwFYzTvi",
                        children: /*#__PURE__*/ _jsx(Instance, {
                            animated: true,
                            className: "framer-qgvfsn",
                            Component: rE1bGiPOa,
                            layoutDependency: layoutDependency,
                            layoutId: "HZ1C_IqLP",
                            style: {
                                "--1m6trwb": 0,
                                "--21h8s6": "var(--token-53318a49-e2d8-4d3b-98d7-8563add13d3d, rgb(56, 56, 61))",
                                "--pgex8v": 1.4
                            }
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-kmaoy8",
                                "data-styles-preset": "MV92va9oP",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-d3c732bc-55cf-476f-8dd2-e130b23f6381, rgb(38, 38, 38)))"
                                },
                                children: "AI Project Tool"
                            })
                        }),
                        className: "framer-1710qob",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "W9bIvDH73",
                        style: {
                            "--extracted-r6o4lv": "var(--token-d3c732bc-55cf-476f-8dd2-e130b23f6381, rgb(38, 38, 38))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: I483A28Gp,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Fhx2V.framer-1ogz9j5, .framer-Fhx2V .framer-1ogz9j5 { display: block; }", ".framer-Fhx2V.framer-18xhfg8 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: min-content; justify-content: center; overflow: hidden; padding: 7px 12px 7px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-Fhx2V .framer-1l1ajhh { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 20px; }", ".framer-Fhx2V .framer-qgvfsn { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }", ".framer-Fhx2V .framer-1710qob { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css, '.framer-Fhx2V[data-border="true"]::after, .framer-Fhx2V [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 34
 * @framerIntrinsicWidth 138.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"rE1bGiPOa":"icon","I483A28Gp":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["omX0gWFPqDwhaiWwf6ab"]
 */
const FramerMQuGF3hFN = withCSS(Component, css, "framer-Fhx2V");
export default FramerMQuGF3hFN;
FramerMQuGF3hFN.displayName = "Badge";
FramerMQuGF3hFN.defaultProps = {
    height: 34,
    width: 138.5
};
addPropertyControls(FramerMQuGF3hFN, {
    rE1bGiPOa: {
        defaultValue: {
            identifier: "module:SUBEdtCFaOJwrjN2Inhk/bznEUerLEqVVXGfsDOYE/pKERsxd4H.js:default",
            moduleId: "SUBEdtCFaOJwrjN2Inhk"
        },
        setModuleId: "omX0gWFPqDwhaiWwf6ab",
        title: "Icon",
        type: ControlType.VectorSetItem
    },
    I483A28Gp: {
        defaultValue: "AI Project Tool",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerMQuGF3hFN, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerMQuGF3hFN",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerVariables": "{\"rE1bGiPOa\":\"icon\",\"I483A28Gp\":\"title\"}",
                "framerIntrinsicHeight": "34",
                "framerContractVersion": "1",
                "framerVectorSets": "[\"omX0gWFPqDwhaiWwf6ab\"]",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "138.5",
                "framerAutoSizeImages": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./MQuGF3hFN.map