// Generated by Framer (4458791)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "fbb60b"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-c7poq", title: siteMetadata(params, activeLocale).title || "Terms Of Use", viewport: "width=1200"}
}

export const metadataVersion = 1