// Generated by Framer (ac3cb42)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: fill ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-WzIzJ", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--21h8s6": ezTt3ayMo,
            ...style
        }
    });
});
const css = ['.framer-WzIzJ { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url(\'data:image/svg+xml,<svg aria-label="Cube" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 18.72 4.7 L 10.47 0.186 L 10.47 0.186 C 10.022 -0.062 9.478 -0.062 9.03 0.186 L 0.78 4.702 C 0.3 4.964 0.001 5.467 0 6.014 L 0 14.98 C 0.001 15.527 0.3 16.03 0.78 16.293 L 9.03 20.809 C 9.478 21.056 10.022 21.056 10.47 20.809 L 18.72 16.293 C 19.2 16.03 19.499 15.527 19.5 14.98 L 19.5 6.015 C 19.5 5.467 19.201 4.963 18.72 4.7 Z M 9.75 1.498 L 9.75 1.498 L 17.282 5.623 L 9.75 9.748 L 2.218 5.623 Z M 1.5 6.936 L 9 11.04 L 9 19.083 L 1.5 14.981 Z M 10.5 19.083 L 10.5 11.044 L 18 6.936 L 18 14.978 Z" fill="var(--21h8s6, rgb(0,0,0))" height="20.99449640570674px" id="X3QqomQ5X" opacity="1" transform="translate(2.25 1.502)" width="19.5px"/></svg>\'); mask-position: center; mask-repeat: no-repeat; width: 24px; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"fill"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Cube","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-WzIzJ");
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "24",
                "framerVariables": "{\"ezTt3ayMo\":\"fill\"}",
                "framerDisableUnlink": "true",
                "framerVector": "{\"name\":\"Cube\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerIntrinsicWidth": "24"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}