// Generated by Framer (6ca5d98)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 3 C 0 1.343 1.343 0 3 0 C 4.657 0 6 1.343 6 3 C 6 4.657 4.657 6 3 6 C 1.343 6 0 4.657 0 3 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="6px" id="MnMvTfj8K" transform="translate(1.5 13.5)" width="6px"/><path d="M 0 3 C 0 1.343 1.343 0 3 0 C 4.657 0 6 1.343 6 3 C 6 4.657 4.657 6 3 6 C 1.343 6 0 4.657 0 3 Z" fill="transparent" height="6px" id="Dnwiz__hf" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(1.5 13.5)" width="6px"/><path d="M 0 0 L 3 3 L 0 6" fill="transparent" height="6px" id="Y84oOl7SB" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(19.5 4.5)" width="3px"/><path d="M 0 9 C 8.25 9 3.75 0 12 0 L 15 0" fill="transparent" height="9px" id="aZ3YVF_T2" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(7.5 7.5)" width="15px"/></svg>';
const getProps = ({
    alpha,
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: color ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)",
        lschgej4H: width1 ? ? props.lschgej4H ? ? 1.5,
        qxTvv_EBh: alpha ? ? props.qxTvv_EBh
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        lschgej4H,
        qxTvv_EBh,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("1283949305", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-dI88f", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m6trwb": qxTvv_EBh,
            "--21h8s6": ezTt3ayMo,
            "--pgex8v": lschgej4H,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-dI88f { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Flow Arrow","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-dI88f");
Icon.displayName = "Flow Arrow";
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    lschgej4H: {
        defaultValue: 1.5,
        displayStepper: true,
        hidden: false,
        max: 6,
        min: 0,
        step: .5,
        title: "Width",
        type: ControlType.Number
    },
    qxTvv_EBh: {
        defaultValue: 0,
        displayStepper: true,
        hidden: false,
        max: 1,
        min: 0,
        step: .1,
        title: "Alpha",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "24",
                "framerVariables": "{\"ezTt3ayMo\":\"color\",\"lschgej4H\":\"width1\",\"qxTvv_EBh\":\"alpha\"}",
                "framerVector": "{\"name\":\"Flow Arrow\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerIntrinsicHeight": "24",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerImmutableVariables": "true",
                "framerDisableUnlink": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}