// Generated by Framer (b012016)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const sB822SU_F = params?.sB822SU_F
return {breakpoints: [{hash: "162mph6", mediaQuery: "(min-width: 1200px)"}, {hash: "yqr2qd", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "t56j11", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {H4UVClOYX: "hreo"}, robots: "max-image-preview:large", serializationId: "framer-nRQvO", title: `${sB822SU_F !== undefined ? toString(sB822SU_F) : "{{sB822SU_F}}"} - ReadyLaunch`, viewport: "width=device-width"}
}

export const metadataVersion = 1