// Generated by Framer (4458791)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "jrpsvp"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-si6Qb", title: siteMetadata(params, activeLocale).title || "Categories", viewport: "width=1200"}
}

export const metadataVersion = 1