// Generated by Framer (c85c929)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1y04hi3", mediaQuery: "(min-width: 1200px)"}, {hash: "zh2kpi", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1wd4hi3", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {B7KBOVYWA: "data-collection", eLn9KgeF0: "data-security", Q6ugQGtKu: "policy-updates", TfFPgYgDR: "data-sharing", WQSD_vw7m: "data-usage", X4WW1QFos: "hero", YwbbuxpK1: "user-rights"}, robots: "max-image-preview:large", serializationId: "framer-qDveA", title: siteMetadata(params, activeLocale).title || "Privacy Policy", viewport: "width=device-width"}
}

export const metadataVersion = 1