// Generated by Framer (6ca5d98)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    useSVGTemplate,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function(props, ref) {
    return /*#__PURE__*/ _jsx("svg", { ...props,
        ref: ref,
        children: props.children
    });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(MotionSVG, { ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children
    }) : /*#__PURE__*/ _jsx("svg", { ...rest,
        ref: ref,
        children: children
    });
});
const svg = '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.495 0 C 10.445 0 7.699 1.847 6.549 4.673 L 6.549 4.663 C 4.579 4.16 2.497 4.839 1.203 6.406 C -0.092 7.973 -0.366 10.146 0.499 11.985 C 1.365 13.824 3.213 14.998 5.245 15 L 13.495 15 C 17.638 15 20.995 11.642 20.995 7.5 C 20.995 3.358 17.638 0 13.495 0 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="15.00000000509916px" id="AzTNGsQqZ" transform="translate(1.505 4.5)" width="20.995466689395847px"/><path d="M 5.994 7.5 C 5.994 3.358 9.351 0 13.494 0 C 17.636 0 20.994 3.358 20.994 7.5 C 20.994 11.642 17.636 15 13.494 15 L 5.244 15 C 3.212 14.997 1.363 13.823 0.499 11.984 C -0.366 10.145 -0.091 7.972 1.203 6.406 C 2.498 4.839 4.58 4.161 6.549 4.663" fill="transparent" height="15px" id="DRJGhCM6Y" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(1.506 4.5)" width="20.993584039658046px"/><path d="M 0 2.25 L 2.25 4.5 L 6.75 0" fill="transparent" height="4.5px" id="MgY0rKi7b" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(11.25 10.5)" width="6.75px"/></svg>';
const getProps = ({
    alpha,
    color,
    height,
    id,
    width,
    width1,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: color ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)",
        lschgej4H: width1 ? ? props.lschgej4H ? ? 1.5,
        qxTvv_EBh: alpha ? ? props.qxTvv_EBh
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        lschgej4H,
        qxTvv_EBh,
        ...restProps
    } = getProps(props);
    const href = useSVGTemplate("2840072777", svg);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-rpolD", className),
        layoutId: layoutId,
        ref: ref,
        role: "presentation",
        style: {
            "--1m6trwb": qxTvv_EBh,
            "--21h8s6": ezTt3ayMo,
            "--pgex8v": lschgej4H,
            ...style
        },
        viewBox: "0 0 24 24",
        children: /*#__PURE__*/ _jsx("use", {
            href: href
        })
    });
});
const css = [`.framer-rpolD { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Cloud Check","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-rpolD");
Icon.displayName = "Cloud Check";
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Color",
        type: ControlType.Color
    },
    lschgej4H: {
        defaultValue: 1.5,
        displayStepper: true,
        hidden: false,
        max: 6,
        min: 0,
        step: .5,
        title: "Width",
        type: ControlType.Number
    },
    qxTvv_EBh: {
        defaultValue: 0,
        displayStepper: true,
        hidden: false,
        max: 1,
        min: 0,
        step: .1,
        title: "Alpha",
        type: ControlType.Number
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerIntrinsicHeight": "24",
                "framerDisableUnlink": "true",
                "framerVariables": "{\"ezTt3ayMo\":\"color\",\"lschgej4H\":\"width1\",\"qxTvv_EBh\":\"alpha\"}",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerVector": "{\"name\":\"Cloud Check\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "24",
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}