// Generated by Framer (ac3cb42)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: fill ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-O9jag", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--21h8s6": ezTt3ayMo,
            ...style
        }
    });
});
const css = ['.framer-O9jag { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url(\'data:image/svg+xml,<svg aria-label="Bounding Box" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 16.5 6 C 17.328 6 18 5.328 18 4.5 L 18 1.5 C 18 0.672 17.328 0 16.5 0 L 13.5 0 C 12.672 0 12 0.672 12 1.5 L 12 2.25 L 6 2.25 L 6 1.5 C 6 0.672 5.328 0 4.5 0 L 1.5 0 C 0.672 0 0 0.672 0 1.5 L 0 4.5 C 0 5.328 0.672 6 1.5 6 L 2.25 6 L 2.25 12 L 1.5 12 C 0.672 12 0 12.672 0 13.5 L 0 16.5 C 0 17.328 0.672 18 1.5 18 L 4.5 18 C 5.328 18 6 17.328 6 16.5 L 6 15.75 L 12 15.75 L 12 16.5 C 12 17.328 12.672 18 13.5 18 L 16.5 18 C 17.328 18 18 17.328 18 16.5 L 18 13.5 C 18 12.672 17.328 12 16.5 12 L 15.75 12 L 15.75 6 Z M 13.5 1.5 L 16.5 1.5 L 16.5 4.5 L 13.5 4.5 Z M 1.5 1.5 L 4.5 1.5 L 4.5 2.991 C 4.499 2.997 4.499 3.003 4.5 3.009 L 4.5 4.5 L 1.5 4.5 Z M 4.5 16.5 L 1.5 16.5 L 1.5 13.5 L 4.5 13.5 L 4.5 14.991 C 4.499 14.997 4.499 15.003 4.5 15.009 Z M 16.5 16.5 L 13.5 16.5 L 13.5 13.5 L 16.5 13.5 Z M 14.25 12 L 13.5 12 C 12.672 12 12 12.672 12 13.5 L 12 14.25 L 6 14.25 L 6 13.5 C 6 12.672 5.328 12 4.5 12 L 3.75 12 L 3.75 6 L 4.5 6 C 5.328 6 6 5.328 6 4.5 L 6 3.75 L 12 3.75 L 12 4.5 C 12 5.328 12.672 6 13.5 6 L 14.25 6 Z" fill="var(--21h8s6, rgb(0,0,0))" height="18px" id="roUgE0jiH" opacity="1" transform="translate(3 3)" width="18px"/></svg>\'); mask-position: center; mask-repeat: no-repeat; width: 24px; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"fill"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Bounding Box","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-O9jag");
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"ezTt3ayMo\":\"fill\"}",
                "framerIntrinsicHeight": "24",
                "framerVector": "{\"name\":\"Bounding Box\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerDisableUnlink": "true",
                "framerContractVersion": "1",
                "framerSupportedLayoutHeight": "any-prefer-fixed",
                "framerIntrinsicWidth": "24",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}