// Generated by Framer (4458791)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["FS;Switzer-regular", "FS;Switzer-bold", "FS;Switzer-bold italic", "FS;Switzer-italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Switzer",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BLNB4FAQFNK56DWWNF7PMGTCOTZHOEII/ST3WKSSDMBK2MIQQO3MAVYWLF4FTOLFV/6IN5WOLRCYP4G4MOCOHOMXNON6Q7MDAR.woff2",
        weight: "400"
    }, {
        family: "Switzer",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HBNTRIISA5MEXGL5WPYI7CV2HIWTDV3Q/YDPDINVT673XLXNSTMLG4JNCZZMVVNPN/Y7SCNZJOT2MW5ADSGOFLDGH4TNL4JCQY.woff2",
        weight: "700"
    }, {
        family: "Switzer",
        source: "fontshare",
        style: "italic",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LVPXCMXCWY3V7PSXRMGRQUJDAS2DT47E/BPEVRT2HG7PPVVUS7A67MZQQZW6LR6A5/A7AS3UPAGLC7MDVC67SBNTE5FGF2Z2RG.woff2",
        weight: "700"
    }, {
        family: "Switzer",
        source: "fontshare",
        style: "italic",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/XVUY2PHYBA6KMN4RMEMJPHQSTKCQ267G/UICOQA6KCSHFOSCPYDVVDNNCDKYFXHJB/O34WRFYO7JNWEBBA2LRV2XYRUSYXYDKH.woff2",
        weight: "400"
    }]
}];
export const css = ['.framer-YF6mi .framer-styles-preset-kmaoy8:not(.rich-text-wrapper), .framer-YF6mi .framer-styles-preset-kmaoy8.rich-text-wrapper p { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-53318a49-e2d8-4d3b-98d7-8563add13d3d, #53535c); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
export const className = "framer-YF6mi";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}