// Generated by Framer (c85c929)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1d6jkqx", mediaQuery: "(min-width: 1200px)"}, {hash: "1p0gbh8", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "39lyzl", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {BaTsuIwJ9: "termination-of-use", MSKjRWout: "acceptance-of-terms", tw0__xUs_: "hero", utiZfywmP: "intellectual-property", wJLkKFr0v: "service-availability", X67h0aTmj: "user-responsibilities"}, robots: "max-image-preview:large", serializationId: "framer-djF6Z", title: siteMetadata(params, activeLocale).title || "Terms Of Use", viewport: "width=device-width"}
}

export const metadataVersion = 1