// Generated by Framer (4458791)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const csQ_aNg27 = params?.csQ_aNg27
return {breakpoints: [{hash: "h88evr"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-zZnlX", title: `${csQ_aNg27 !== undefined ? toString(csQ_aNg27) : "{{csQ_aNg27}}"} - ReadyLaunch`, viewport: "width=1200"}
}

export const metadataVersion = 1