// Generated by Framer (570e25b)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "ozjdfx", mediaQuery: "(min-width: 1200px)"}, {hash: "j7vd08", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "10guly9", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {xJmCXxJZB: "hero"}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-DoUlU", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1