// Generated by Framer (6464825)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const JIXZXkrm_ = params?.JIXZXkrm_
return {breakpoints: [{hash: "upz6ry"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-SQzps", title: `${JIXZXkrm_ !== undefined ? toString(JIXZXkrm_) : "{{JIXZXkrm_}}"} - ReadyLaunch`, viewport: "width=1200"}
}

export const metadataVersion = 1