// Generated by Framer (b012016)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "168a2ci", mediaQuery: "(min-width: 1200px)"}, {hash: "1t87pnm", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "3kvc58", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {J9abzzAns: "hero"}, robots: "max-image-preview:large", serializationId: "framer-RbYuL", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=device-width"}
}

export const metadataVersion = 1