// Generated by Framer (570e25b)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import NumberCounter from "https://framerusercontent.com/modules/ToDnDaiDYJNi85IQjmYu/v4yDfgV04HSZjwMKHjPq/NumberCounter.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/4AgsUj8M4cU5xdkJd6F0/ePSITNvvWIiML1i7Q0Ln/OvgFe4dMx.js";
import * as sharedStyle from "https://framerusercontent.com/modules/baLMLPsY3wTBmzHdwsAK/LGUrz1oqt36oQVGCAdPn/xhIf5qL2n.js";
const NumberCounterFonts = getFonts(NumberCounter);
const cycleOrder = ["ZW74XCmJ2", "WzU27KU1d"];
const serializationHash = "framer-JxHMO";
const variantClassNames = {
    WzU27KU1d: "framer-v-xomy8p",
    ZW74XCmJ2: "framer-v-1c2l40y"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Phone: "WzU27KU1d",
    Primary: "ZW74XCmJ2"
};
const getProps = ({
    decimals,
    duration,
    end,
    height,
    id,
    suffix,
    text,
    title,
    width,
    ...props
}) => {
    return { ...props,
        aReiDA58n: end ? ? props.aReiDA58n ? ? 120,
        dxuuy543a: text ? ? props.dxuuy543a ? ? "Thousands of workflows run every single week.",
        FECcnJmfO: decimals ? ? props.FECcnJmfO,
        sdGxgQBhr: title ? ? props.sdGxgQBhr ? ? "Tasks Managed Weekly",
        TLdXilcg1: suffix ? ? props.TLdXilcg1 ? ? "+",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "ZW74XCmJ2",
        xmornl7sR: duration ? ? props.xmornl7sR ? ? 1
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        aReiDA58n,
        TLdXilcg1,
        sdGxgQBhr,
        dxuuy543a,
        FECcnJmfO,
        xmornl7sR,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "ZW74XCmJ2",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1c2l40y", className, classNames),
                    "data-border": true,
                    "data-framer-name": "Primary",
                    layoutDependency: layoutDependency,
                    layoutId: "ZW74XCmJ2",
                    ref: refBinding,
                    style: {
                        "--border-bottom-width": "1px",
                        "--border-color": "var(--token-64e377a5-0d6a-419d-892d-eb08deb7230b, rgb(229, 229, 232))",
                        "--border-left-width": "1px",
                        "--border-right-width": "1px",
                        "--border-style": "solid",
                        "--border-top-width": "1px",
                        backgroundColor: "var(--token-e1c52d29-6b20-4ee3-afb3-f179ac191e9c, rgb(251, 251, 251))",
                        borderBottomLeftRadius: 10,
                        borderBottomRightRadius: 10,
                        borderTopLeftRadius: 10,
                        borderTopRightRadius: 10,
                        boxShadow: "0px 3px 5px 0px var(--token-0c21c7c4-decf-4cb8-98b2-1f4ecf98c018, rgb(248, 249, 250))",
                        ...style
                    },
                    ...addPropertyOverrides({
                        WzU27KU1d: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-sqwghv-container",
                            "data-code-component-plugin-id": "84d4c1",
                            isAuthoredByUser: true,
                            layoutDependency: layoutDependency,
                            layoutId: "tFW2Walvu-container",
                            nodeId: "tFW2Walvu",
                            rendersWithMotion: true,
                            scopeId: "fl1vas1Ab",
                            children: /*#__PURE__*/ _jsx(NumberCounter, {
                                color: "var(--token-d602a9d1-da3b-45d6-b039-eac0d7c79341, rgb(66, 135, 255))",
                                decimals: FECcnJmfO,
                                duration: xmornl7sR,
                                endNumber: aReiDA58n,
                                font: {
                                    fontFamily: '"Inter", "Inter Placeholder", sans-serif',
                                    fontSize: "60px",
                                    fontStyle: "normal",
                                    fontWeight: 500,
                                    letterSpacing: "-0.04em",
                                    lineHeight: "1em"
                                },
                                height: "100%",
                                id: "tFW2Walvu",
                                layoutId: "tFW2Walvu",
                                prefix: "",
                                startNumber: 0,
                                suffix: TLdXilcg1,
                                trigger: "layer",
                                width: "100%",
                                ...addPropertyOverrides({
                                    WzU27KU1d: {
                                        font: {
                                            fontFamily: '"Switzer", "Switzer Placeholder", sans-serif',
                                            fontSize: "40px",
                                            fontStyle: "normal",
                                            fontWeight: 500,
                                            letterSpacing: "-0.02em",
                                            lineHeight: "1em"
                                        }
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-k5r3gi",
                        "data-framer-name": "Heading & Supporting Text",
                        layoutDependency: layoutDependency,
                        layoutId: "qPFA0m_DB",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h6, {
                                    className: "framer-styles-preset-ggytww",
                                    "data-styles-preset": "xhIf5qL2n",
                                    style: {
                                        "--framer-text-alignment": "left"
                                    },
                                    children: "Tasks Managed Weekly"
                                })
                            }),
                            className: "framer-oxrbuq",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "pgsnJOi2Q",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: sdGxgQBhr,
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                WzU27KU1d: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.h5, {
                                            className: "framer-styles-preset-ggytww",
                                            "data-styles-preset": "xhIf5qL2n",
                                            style: {
                                                "--framer-text-alignment": "left"
                                            },
                                            children: "Tasks Managed Weekly"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-wct5n4",
                                    "data-styles-preset": "OvgFe4dMx",
                                    style: {
                                        "--framer-text-alignment": "left"
                                    },
                                    children: "Thousands of workflows run every single week."
                                })
                            }),
                            className: "framer-w7jbr6",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "AEAu_WOc2",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: dxuuy543a,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-JxHMO.framer-xj606s, .framer-JxHMO .framer-xj606s { display: block; }", ".framer-JxHMO.framer-1c2l40y { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 105px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 40px 30px 30px 30px; position: relative; width: 327px; will-change: var(--framer-will-change-override, transform); }", ".framer-JxHMO .framer-sqwghv-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-JxHMO .framer-k5r3gi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-JxHMO .framer-oxrbuq, .framer-JxHMO .framer-w7jbr6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-JxHMO.framer-v-xomy8p.framer-1c2l40y { gap: 60px; padding: 25px; width: 253px; }", ".framer-JxHMO.framer-v-xomy8p .framer-k5r3gi { gap: 5px; }", ...sharedStyle.css, ...sharedStyle1.css, '.framer-JxHMO[data-border="true"]::after, .framer-JxHMO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 311.5
 * @framerIntrinsicWidth 326.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"WzU27KU1d":{"layout":["fixed","auto"]}}}
 * @framerVariables {"aReiDA58n":"end","TLdXilcg1":"suffix","sdGxgQBhr":"title","dxuuy543a":"text","FECcnJmfO":"decimals","xmornl7sR":"duration"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const Framerfl1vas1Ab = withCSS(Component, css, "framer-JxHMO");
export default Framerfl1vas1Ab;
Framerfl1vas1Ab.displayName = "Metrics";
Framerfl1vas1Ab.defaultProps = {
    height: 311.5,
    width: 326.5
};
addPropertyControls(Framerfl1vas1Ab, {
    variant: {
        options: ["ZW74XCmJ2", "WzU27KU1d"],
        optionTitles: ["Primary", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    aReiDA58n: {
        defaultValue: 120,
        displayStepper: true,
        max: 999999,
        min: 0,
        title: "End",
        type: ControlType.Number
    },
    TLdXilcg1: {
        defaultValue: "+",
        placeholder: "e.g. %",
        title: "Suffix",
        type: ControlType.String
    },
    sdGxgQBhr: {
        defaultValue: "Tasks Managed Weekly",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    dxuuy543a: {
        defaultValue: "Thousands of workflows run every single week.",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    },
    FECcnJmfO: {
        defaultValue: 0,
        displayStepper: true,
        max: 6,
        min: 0,
        step: 1,
        title: "Decimals",
        type: ControlType.Number
    },
    xmornl7sR: {
        defaultValue: 1,
        max: 5,
        min: .2,
        step: .1,
        title: "Duration",
        type: ControlType.Number
    }
});
addFonts(Framerfl1vas1Ab, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
        weight: "500"
    }, {
        family: "Switzer",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/OYB4CXKJQXKTNSLJMTDQOIVUL2V5EL7S/WYO2P7DQVV5RNXGMCUO2HL4RJP4VFUAS/6XPIMU23OJVRY676OG5YVJMWEHWICATX.woff2",
        weight: "500"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...NumberCounterFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framerfl1vas1Ab",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerVariables": "{\"aReiDA58n\":\"end\",\"TLdXilcg1\":\"suffix\",\"sdGxgQBhr\":\"title\",\"dxuuy543a\":\"text\",\"FECcnJmfO\":\"decimals\",\"xmornl7sR\":\"duration\"}",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "311.5",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"WzU27KU1d\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "326.5"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}